In [15]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv('calls-20260302222425.csv')

In [17]:
# Add this right after loading the raw CSV (around cell where you do pd.read_csv('calls-20260302222425.csv'))

# Check for missing dates
print(f"Rows with missing dates: {df['_readable_date'].isna().sum()}")
print("\nSample of rows with missing dates:")
print(df[df['_readable_date'].isna()][['_readable_date', '_contact_name', '_number', '_duration']].head(10))

# Option 1: Drop rows with missing dates
df = df.dropna(subset=['_readable_date'])

# OR Option 2: Try to infer dates from context (if there's a pattern)
# This would require examining the raw CSV structure

Rows with missing dates: 0

Sample of rows with missing dates:
Empty DataFrame
Columns: [_readable_date, _contact_name, _number, _duration]
Index: []

In [18]:
df.columns

Index(['_number', '_duration', '_date', '_type', '_presentation',
       '_subscription_id', '_post_dial_digits', '_subscription_component_name',
       '_readable_date', '_contact_name'],
      dtype='object')

In [19]:
names = df['_contact_name'].unique()
dic = {name: f'Person-{i+1}' for i, name in enumerate(names) if name != '(Unknown)'}
df['_contact_name'] = df['_contact_name'].map(lambda x: dic.get(x, 'Unknown'))

In [ ]:
ind = df['_number'] == '.'
df.loc[ind, '_number'] = '+972.'

ind = df['_number'] == '.'
df.loc[ind, '_number'] = '+972.'

ind = df['_number'].str.startswith('054')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('054', '+97254', regex=False)
# 052
ind = df['_number'].str.startswith('052')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('052', '+97252', regex=False)

# 04
ind = df['_number'].str.startswith('04')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('04', '+9724', regex=False)

# 09
ind = df['_number'].str.startswith('09')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('09', '+9729', regex=False)


# numbers starting with 039 are German and need to add +49 and remover the leading 0
ind = df['_number'].str.startswith('039')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('039', '+4939', regex=False)

ind = df['_number'].str.startswith('016')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('016', '+4916', regex=False)

# 030
ind = df['_number'].str.startswith('030')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('030', '+493', regex=False)

# 017
ind = df['_number'].str.startswith('017')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('017', '+4917', regex=False)

# 033
ind = df['_number'].str.startswith('033')
ind[ind != True] = False
df.loc[ind, '_number'] = df.loc[ind, '_number'].str.replace('033', '+4933', regex=False)

In [21]:
ind = df['_number'].str.startswith('+') == False
ind[ind != True] = False
df.loc[ind, '_number'].unique()

array(['*2250', '*6016', '0732095770', '1800800677', '*6428',
       '089787979400', '08004555500', '658086869', '08002858585'],
      dtype=object)

In [22]:
df['_number'].unique()

df.to_csv('calls-20260302222425-anonymized.csv', index=False)

In [23]:
df = pd.read_csv('calls-20260302222425-anonymized.csv')

In [24]:
# permutation of the numbers and then replace the last 2 digits and leaving all as is
# 1. Set the NumPy random seed
np.random.seed(np.random.permutation(10))

# 2. Generate the permutation directly
permutation = np.random.permutation(10)

dic_perm = {str(i): str(permutation[i]) for i in range(10)}

f = lambda x: x[0:4] + '-' + dic_perm.get(x[-1], x[-1]) + dic_perm.get(x[-2], x[-2]) if isinstance(x, str) else None
df['_number'] = df['_number'].map(f)

In [25]:
df.to_csv('calls-20260302222425-anonymized-permuted.csv', index=False)

In [36]:
# load data
df = pd.read_csv('calls-20260302222425-anonymized-permuted.csv')
df

,_number,_duration,_date,_type,_presentation,_subscription_id,_post_dial_digits,_subscription_component_name,_readable_date,_contact_name
0,+972-84,0,1654769333338,3,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,9 Jun 2022 12:08:53,Unknown
1,+972-17,0,1655030243686,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,12 Jun 2022 12:37:23,Unknown
2,+972-15,0,1655202115387,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,14 Jun 2022 12:21:55,Unknown
3,+972-72,0,1655203032593,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,14 Jun 2022 12:37:12,Unknown
4,+972-87,0,1655365893370,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,16 Jun 2022 09:51:33,Unknown
...,...,...,...,...,...,...,...,...,...,...
1075,+491-46,34,1772213311986,1,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,27 Feb 2026 18:28:31,Person-8
1076,+491-55,0,1772310885813,3,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,28 Feb 2026 21:34:45,Person-11
1077,+491-55,202,1772356693125,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 10:18:13,Person-11
1078,+491-55,202,1772356693125,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 10:18:13,Person-11
1079,+491-46,40,1772372106822,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 14:35:06,Person-8

In [37]:
# i want to add a column is_known that is True if the contact name starts with 'Person' and False otherwise
df['is_known'] = df['_contact_name'].str.startswith('Person')

In [38]:
df

,_number,_duration,_date,_type,_presentation,_subscription_id,_post_dial_digits,_subscription_component_name,_readable_date,_contact_name,is_known
0,+972-84,0,1654769333338,3,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,9 Jun 2022 12:08:53,Unknown,False
1,+972-17,0,1655030243686,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,12 Jun 2022 12:37:23,Unknown,False
2,+972-15,0,1655202115387,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,14 Jun 2022 12:21:55,Unknown,False
3,+972-72,0,1655203032593,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,14 Jun 2022 12:37:12,Unknown,False
4,+972-87,0,1655365893370,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,16 Jun 2022 09:51:33,Unknown,False
...,...,...,...,...,...,...,...,...,...,...,...
1075,+491-46,34,1772213311986,1,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,27 Feb 2026 18:28:31,Person-8,True
1076,+491-55,0,1772310885813,3,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,28 Feb 2026 21:34:45,Person-11,True
1077,+491-55,202,1772356693125,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 10:18:13,Person-11,True
1078,+491-55,202,1772356693125,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 10:18:13,Person-11,True
1079,+491-46,40,1772372106822,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 14:35:06,Person-8,True

In [39]:
# Use phonenumbers to extract calling code and map to country/region
%pip -q install phonenumbers

import phonenumbers
from phonenumbers import NumberParseException

def parse_phone_meta(number):
    if not isinstance(number, str) or not number.startswith('+'):
        return pd.Series({'tel_code': pd.NA, 'country': pd.NA})
    try:
        parsed = phonenumbers.parse(number, None)
        tel_code = f"+{parsed.country_code}"
        country = phonenumbers.region_code_for_number(parsed) or pd.NA
        return pd.Series({'tel_code': tel_code, 'country': country})
    except NumberParseException:
        return pd.Series({'tel_code': pd.NA, 'country': pd.NA})

df[['tel_code', 'country']] = df['_number'].apply(parse_phone_meta)
df[['tel_code', 'country']].head()

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

  tel_code country
0     +972      IL
1     +972      IL
2     +972      IL
3     +972      IL
4     +972      IL

In [40]:
# Add is_EU: True for EU countries, False for non-EU, None for unknown
EU_COUNTRIES = {
    'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR',
    'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL',
    'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'
}

def to_is_eu(country_code):
    if pd.isna(country_code):
        return None
    return country_code in EU_COUNTRIES

df['is_EU'] = df['country'].apply(to_is_eu)
df[['country', 'is_EU']].head(20)

   country  is_EU
0       IL  False
1       IL  False
2       IL  False
3       IL  False
4       IL  False
5       DE   True
6       DE   True
7       DE   True
8       DE   True
9       DE   True
10    <NA>   None
11      IL  False
12      IL  False
13      IL  False
14      IL  False
15      IL  False
16      IL  False
17      IL  False
18      IL  False
19      IL  False

In [41]:

# convert to the datetime
# df['date'] = pd.to_datetime(df['_readable_date'], errors='coerce')
def parse_date_flexible(date_str):
    if pd.isna(date_str):
        return pd.NaT

    formats = [
        '%Y-%m-%d %H:%M:%S',  # Standard: 2025-09-16 12:30:00
        '%d/%m/%Y %H:%M:%S',  # European: 16/09/2025 12:30:00
        '%m/%d/%Y %H:%M:%S',  # US: 09/16/2025 12:30:00
        '%Y-%m-%d',           # Date only
        '%d.%m.%Y %H:%M:%S',  # German: 16.09.2025 12:30:00
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(date_str, format=fmt)
        except:
            continue

    # Fallback to pandas auto-parser
    return pd.to_datetime(date_str, errors='coerce')

df['date'] = df['_readable_date'].apply(parse_date_flexible)

# Add diagnostic check HERE:
print(f"\n🔍 Date conversion diagnostics:")
print(f"Original _readable_date nulls: {df['_readable_date'].isna().sum()}")
print(f"Converted date nulls: {df['date'].isna().sum()}")
print(f"Conversion failures (NaT): {df['date'].isna().sum() - df['_readable_date'].isna().sum()}")

# Show failed conversions
if df['date'].isna().sum() > 0:
    print(f"\n⚠️ Failed date conversions:")
    failed = df[df['date'].isna()][['_readable_date', '_contact_name', '_number']].head(20)
    print(failed)

    # Show unique date formats that failed
    print(f"\n📋 Unique date strings that failed to parse:")
    print(df[df['date'].isna()]['_readable_date'].unique()[:10])

🔍 Date conversion diagnostics:
Original _readable_date nulls: 0
Converted date nulls: 0
Conversion failures (NaT): 0

/var/folders/tw/07_5xg2d4wjgfywl8ndc_7mh0000gp/T/ipykernel_85871/403252486.py:22: UserWarning: Parsing dates in %d Sept %Y %H:%m:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce')
/var/folders/tw/07_5xg2d4wjgfywl8ndc_7mh0000gp/T/ipykernel_85871/403252486.py:22: UserWarning: Parsing dates in %d Sept %Y %m:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce')

In [42]:
ind = df['is_EU'] == False
df.loc[ind, 'country'] = 'Non-EU'

In [43]:
df['duration_sec'] = pd.to_numeric(df['_duration'], errors='coerce')

In [44]:
df

,_number,_duration,_date,_type,_presentation,_subscription_id,_post_dial_digits,_subscription_component_name,_readable_date,_contact_name,is_known,tel_code,country,is_EU,date,duration_sec
0,+972-84,0,1654769333338,3,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,9 Jun 2022 12:08:53,Unknown,False,+972,Non-EU,False,2022-06-09 12:08:53,0
1,+972-17,0,1655030243686,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,12 Jun 2022 12:37:23,Unknown,False,+972,Non-EU,False,2022-06-12 12:37:23,0
2,+972-15,0,1655202115387,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,14 Jun 2022 12:21:55,Unknown,False,+972,Non-EU,False,2022-06-14 12:21:55,0
3,+972-72,0,1655203032593,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,14 Jun 2022 12:37:12,Unknown,False,+972,Non-EU,False,2022-06-14 12:37:12,0
4,+972-87,0,1655365893370,5,1,89972080091096695909,NaN,com.android.phone/com.android.services.telepho...,16 Jun 2022 09:51:33,Unknown,False,+972,Non-EU,False,2022-06-16 09:51:33,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,+491-46,34,1772213311986,1,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,27 Feb 2026 18:28:31,Person-8,True,+49,DE,True,2026-02-27 18:28:31,34
1076,+491-55,0,1772310885813,3,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,28 Feb 2026 21:34:45,Person-11,True,+49,DE,True,2026-02-28 21:34:45,0
1077,+491-55,202,1772356693125,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 10:18:13,Person-11,True,+49,DE,True,2026-03-01 10:18:13,202
1078,+491-55,202,1772356693125,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 10:18:13,Person-11,True,+49,DE,True,2026-03-01 10:18:13,202
1079,+491-46,40,1772372106822,2,1,8949360000373823966F,NaN,com.android.phone/com.android.services.telepho...,1 Mar 2026 14:35:06,Person-8,True,+49,DE,True,2026-03-01 14:35:06,40

In [45]:
# columns to save for processing
cols_to_save = ['date', 'is_known', 'is_EU', 'country', 'duration_sec']
df[cols_to_save].head()

                 date  is_known  is_EU country  duration_sec
0 2022-06-09 12:08:53     False  False  Non-EU             0
1 2022-06-12 12:37:23     False  False  Non-EU             0
2 2022-06-14 12:21:55     False  False  Non-EU             0
3 2022-06-14 12:37:12     False  False  Non-EU             0
4 2022-06-16 09:51:33     False  False  Non-EU             0

In [46]:
# save data
df[cols_to_save].to_csv('data-processed.csv', index=False)

In [47]:
# load data
df = pd.read_csv('data-processed.csv')

In [ ]:
df

In [48]:
# === ANALYSIS SETUP: Define Periods, Triggers, and Windows ===

# 1. Define analysis periods/stages
periods = {
    'Baseline (Pre-Audit)': ('2022-06-09', '2025-08-02'),
    'Phase 1: Invisible (RU/BY)': ('2025-08-03', '2025-09-15'),
    'Phase 2: Visible (DE/UA/Public)': ('2025-09-16', '2025-11-18'),
    'Phase 3: Manifestation (Performance/AGI)': ('2025-11-19', '2026-02-28')
}

# 2. Define trigger dates (key events)
trigger_dates = [
    '2025-08-03',  # First message NAVERH
    '2025-09-16',  # Public confession
    '2025-09-19',  # Sternenko challenge
    '2025-11-19',  # Bundestag solo performance
    '2026-01-07',  # CogOS v0.1 release
    '2026-01-15',  # TIK final synthesis
    '2026-02-24',  # SVE vs Experts
    '2026-02-27'   # Final README / Austria anomaly
]

# Convert trigger dates to datetime
trigger_dates_dt = [pd.to_datetime(d) for d in trigger_dates]

print("✓ Periods defined:")
for name, (start, end) in periods.items():
    print(f"  {name}: {start} to {end}")

print(f"\n✓ {len(trigger_dates)} trigger dates loaded")
print(f"✓ Windows: 48h (±2d), 7d (±3.5d), 1M (±15d)")

# save these info nicely as yaml
import yaml
config = {
    'periods': {name: {'start': start, 'end': end} for name, (start, end) in periods.items()},
    'trigger_dates': trigger_dates,
    'windows': {
        '48h': {'before': '2d', 'after': '2d'},
        '7d': {'before': '3.5d', 'after': '3.5d'},
        '1M': {'before': '15d', 'after': '15d'}
    }
}
with open('analysis_config.yaml', 'w') as f:
    yaml.dump(config, f)

✓ Periods defined:
  Baseline (Pre-Audit): 2022-06-09 to 2025-08-02
  Phase 1: Invisible (RU/BY): 2025-08-03 to 2025-09-15
  Phase 2: Visible (DE/UA/Public): 2025-09-16 to 2025-11-18
  Phase 3: Manifestation (Performance/AGI): 2025-11-19 to 2026-02-28

✓ 8 trigger dates loaded
✓ Windows: 48h (±2d), 7d (±3.5d), 1M (±15d)

In [49]:
# load config
with open('analysis_config.yaml', 'r') as f:
    config = yaml.safe_load(f)
periods = {name: (pd.to_datetime(info['start']), pd.to_datetime(info['end'])) for name, info in config['periods'].items()}
trigger_dates_dt = [pd.to_datetime(d) for d in config['trigger_dates']]

In [50]:
# === ADD ANALYSIS COLUMNS ===

# Function to categorize each call into a period
def categorize_period(call_date):
    if pd.isna(call_date):
        return 'Unknown'

    for period_name, (start, end) in periods.items():
        if pd.to_datetime(start) <= call_date <= pd.to_datetime(end):
            return period_name

    return 'Out of range'

# Function to check if call is within trigger windows
def check_trigger_windows(call_date):
    if pd.isna(call_date):
        return {'48h': False, '7d': False, '1M': False}

    windows = {'48h': False, '7d': False, '1M': False}

    for trigger_dt in trigger_dates_dt:
        delta_days = abs((call_date - trigger_dt).days)

        if delta_days <= 2:  # 48h window
            windows['48h'] = True
        if delta_days <= 3.5:  # 7d window (approximately)
            windows['7d'] = True
        if delta_days <= 15:  # 1 month window
            windows['1M'] = True

    return windows

# Apply period categorization
df['analysis_period'] = df['date'].apply(lambda x: categorize_period(pd.to_datetime(x, errors='coerce')))

# Apply trigger window checks
trigger_results = df['date'].apply(lambda x: check_trigger_windows(pd.to_datetime(x, errors='coerce')))
df['trigger_48h'] = trigger_results.apply(lambda x: x['48h'])
df['trigger_7d'] = trigger_results.apply(lambda x: x['7d'])
df['trigger_1M'] = trigger_results.apply(lambda x: x['1M'])

# Display summary
print("✓ Added columns:")
print("  - analysis_period: categorizes each call into a period")
print("  - trigger_48h: True if within ±2 days of any trigger")
print("  - trigger_7d: True if within ±3.5 days of any trigger")
print("  - trigger_1M: True if within ±15 days of any trigger")
print(f"\n{df.columns.tolist()}")

✓ Added columns:
  - analysis_period: categorizes each call into a period
  - trigger_48h: True if within ±2 days of any trigger
  - trigger_7d: True if within ±3.5 days of any trigger
  - trigger_1M: True if within ±15 days of any trigger

['date', 'is_known', 'is_EU', 'country', 'duration_sec', 'analysis_period', 'trigger_48h', 'trigger_7d', 'trigger_1M']

In [51]:
# === SUMMARY STATISTICS BY PERIOD ===

# Calculate stats for each period
period_stats = []
for period_name, (start, end) in periods.items():
    mask = df['analysis_period'] == period_name
    period_calls = df[mask]

    num_days = (pd.to_datetime(end) - pd.to_datetime(start)).days + 1
    total = len(period_calls)
    unknown = (period_calls['is_known'] == False).sum()
    eu = (period_calls['is_EU'] == True).sum()
    non_eu = (period_calls['is_EU'] == False).sum()

    period_stats.append({
        'Period': period_name,
        'Days': num_days,
        'Total Calls': total,
        'Unknown': unknown,
        'EU': eu,
        'Non-EU': non_eu,
        'Avg/day': round(total / num_days, 2)
    })

stats_df = pd.DataFrame(period_stats)
print("Period Statistics:")
print(stats_df.to_string(index=False))

# Trigger window summary
print("\n\nTrigger Window Statistics:")
trigger_summary = pd.DataFrame({
    'Window': ['48h (±2d)', '7d (±3.5d)', '1M (±15d)'],
    'Total Calls': [
        df['trigger_48h'].sum(),
        df['trigger_7d'].sum(),
        df['trigger_1M'].sum()
    ],
    'Unknown': [
        df[df['trigger_48h']]['is_known'].apply(lambda x: not x).sum(),
        df[df['trigger_7d']]['is_known'].apply(lambda x: not x).sum(),
        df[df['trigger_1M']]['is_known'].apply(lambda x: not x).sum()
    ]
})
print(trigger_summary.to_string(index=False))

Period Statistics:
                                  Period  Days  Total Calls  Unknown  EU  Non-EU  Avg/day
                    Baseline (Pre-Audit)  1151          831      276 610     175     0.72
              Phase 1: Invisible (RU/BY)    44           88       23  80       1     2.00
         Phase 2: Visible (DE/UA/Public)    64           79       18  77       1     1.23
Phase 3: Manifestation (Performance/AGI)   102           78       22  66       7     0.76


Trigger Window Statistics:
    Window  Total Calls  Unknown
 48h (±2d)           42       17
7d (±3.5d)           56       17
 1M (±15d)          186       44

In [52]:
# store data for analysis
df.to_csv('data-for-analysis.csv', index=False)

In [ ]:
# # load config
# with open('analysis_config.yaml', 'r') as f:
#     config = yaml.safe_load(f)
# periods = {name: (pd.to_datetime(info['start']), pd.to_datetime(info['end'])) for name, info in config['periods'].items()}
# trigger_dates_dt = [pd.to_datetime(d) for d in config['trigger_dates']]

In [ ]:
# read a list of items in markdown

df = pd.read_csv('/Users/artiom/Desktop/addressants.md')